version: '3.8'

services:
  api:
    build: ./api
    env_file:
      - ./api/.env
    container_name: api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - '3001'
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./admin-dist:/var/www/admin-dist
      - ./user-dist:/var/www/user-dist
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jjdesign
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
